/*
 * Copyright 2006, ZiLOG Inc.
 * All Rights Reserved
 *
 * This is UNPUBLISHED PROPRIETARY SOURCE CODE of ZiLOG Inc., and might
 * contain proprietary, confidential and trade secret information of
 * ZiLOG, our partners and parties from which this code has been licensed.
 * 
 * The contents of this file may not be disclosed to third parties, copied or
 * duplicated in any form, in whole or in part, without the prior written
 * permission of ZiLOG Inc.
 */
#ifndef _TB_MSG_H_
#define _TB_MSG_H_


typedef enum MGS_ID_E {
SIM_MSG_TEST_START                  = 0x00,

//--- Default Vector Messages
SIM_MSG_UNDEFINED                   = 0x01,
SIM_MSG_SWI                         = 0x02,
SIM_MSG_PREFETCH                    = 0x03,
SIM_MSG_ABORT                       = 0x04,
SIM_MSG_RESERVED                    = 0x05,
SIM_MSG_IRQ                         = 0x06,
SIM_MSG_FIQ                         = 0x07,

//--- Generic Test Messages
SIM_MSG_ERROR_STEP                  = 0x08,
SIM_MSG_START_STEP                  = 0x09,
SIM_MSG_START_DMA                   = 0x0A,
SIM_MSG_MEM_COMPARE_ERR             = 0x0B,
SIM_MSG_VIC_ERR                     = 0x0C,
SIM_MSG_ERROR_RESET                 = 0x0D,
SIM_MSG_ERROR_CLOCK_RUN             = 0x0E,

//--- Interrupt Messages
SIM_MSG_TIMER0_INTR                 = 0x10,
SIM_MSG_TIMER1_INTR                 = 0x11,
SIM_MSG_TIMER2_INTR                 = 0x12,
SIM_MSG_TIMER3_INTR                 = 0x13,
SIM_MSG_TIMER4_INTR                 = 0x14,
SIM_MSG_TIMER5_INTR                 = 0x15,
SIM_MSG_TIMER6_INTR                 = 0x16,
SIM_MSG_TIMER7_INTR                 = 0x17,
SIM_MSG_TIMER8_INTR                 = 0x18,
SIM_MSG_WDT_INTR                    = 0x19,
SIM_MSG_UART0_INTR                  = 0x1A,
SIM_MSG_UART1_INTR                  = 0x1B,
SIM_MSG_UART2_INTR                  = 0x1C,
SIM_MSG_UART_RX                     = 0x1D,
SIM_MSG_UART_TX                     = 0x1E,
SIM_MSG_UART_RX_ERR                 = 0x1F,
SIM_MSG_UART_ERR                    = 0x20,
SIM_MSG_UART_TO_ERR                 = 0x21,
SIM_MSG_SPI4_INTR                   = 0x22,
SIM_MSG_MCR_INTR                    = 0x23,
SIM_MSG_DAA_INTR                    = 0x24,
SIM_MSG_SDD_INTR                    = 0x25,
SIM_MSG_GPIO0_INTR                  = 0x26,
SIM_MSG_GPIO1_INTR                  = 0x27,
SIM_MSG_GPIO2_INTR                  = 0x28,
SIM_MSG_GPIO3_INTR                  = 0x29,
SIM_MSG_SPI2_INTR                   = 0x2A,
SIM_MSG_RNG_INTR                    = 0x2B,
SIM_MSG_USB0_INTR                   = 0x2C,
SIM_MSG_USB1_INTR                   = 0x2D,
SIM_MSG_USB2_INTR                   = 0x2E,
SIM_MSG_SPI3_INTR                   = 0x2F,
SIM_MSG_ADC_INTR                    = 0x30,
SIM_MSG_SPI0_INTR                   = 0x31,
SIM_MSG_SPI1_INTR                   = 0x32,
SIM_MSG_RTC_INTR                    = 0x33,
SIM_MSG_I2C_INTR                    = 0x34,
SIM_MSG_DMA_ERROR                   = 0x35,
SIM_MSG_START_DMA_MEM_MEM           = 0x36,
SIM_MSG_START_ADDR_VERIF            = 0x37,
SIM_MSG_START_ADDR_TEST             = 0x38,
SIM_MSG_START_BURST_TEST            = 0x39,
SIM_MSG_START_TIMER                 = 0x3A,
SIM_MSG_START_DMA_MEM_PER           = 0x3B,
SIM_MSG_START_DMA_PER_MEM           = 0x3C,
SIM_MSG_RTC_START                   = 0x3D,
SIM_MSG_START_SDRAM                 = 0x3E,
SIM_MSG_START_SPI                   = 0x3F,
SIM_MSG_STOP_TIMER                  = 0x40,
SIM_MSG_TIMER_NO_INTR               = 0x41,
SIM_MSG_TIMER0_END                  = 0x42,
SIM_MSG_TIMER1_END                  = 0x43,
SIM_MSG_TIMER2_END                  = 0x44,
SIM_MSG_TIMER3_END                  = 0x45,
SIM_MSG_TIMER4_END                  = 0x46,
SIM_MSG_TIMER5_END                  = 0x47,
SIM_MSG_TIMER6_END                  = 0x48,
SIM_MSG_TIMER7_END                  = 0x49,
SIM_MSG_TIMER8_END                  = 0x4A,
SIM_MSG_INIT_UART                   = 0x4B,
SIM_MSG_INIT_RNG                    = 0x4C,
SIM_MSG_SPI_ERR                     = 0x4D,
SIM_MSG_SPI_RX_OV_ERR               = 0x4E,
SIM_MSG_MASTER_COLLISION            = 0x4F,
SIM_MSG_SPI_SLAVE_ABORT             = 0x50,
SIM_MSG_SPI_RECV_ERR                = 0x51,
SIM_MSG_SPI_RX_DONE                 = 0x52,
SIM_MSG_SPI_TX_DONE                 = 0x53,
SIM_MSG_SPI_TX_OV_ERR               = 0x54,
SIM_MSG_INIT_GPIO                   = 0x55,
SIM_MSG_SPI_ONE_END                 = 0x56,

//--- USB0 outputs
SIM_MSG_USB_INT_RESET               = 0x57,
SIM_MSG_USB_INT_ERROR               = 0x58,
SIM_MSG_USB_INT_SOF                 = 0x59,
SIM_MSG_USB_INT_TOKEN_DONE          = 0x5A,
SIM_MSG_USB_INT_SLEEP               = 0x5B,
SIM_MSG_USB_INT_RESUME              = 0x5C,
SIM_MSG_USB_INT_ATTACH              = 0x5D,
SIM_MSG_USB_INT_STALL               = 0x5E,
SIM_MSG_USB_START_RESET             = 0x5F,
SIM_MSG_USB_STOP_RESET              = 0x60,
SIM_MSG_USB_ATTACH_HIGH             = 0x61,
SIM_MSG_USB_ATTACH_LOW              = 0x62,
SIM_MSG_USB_PID_ERROR               = 0x63,
SIM_MSG_USB_CRC5_ERROR              = 0x64,
SIM_MSG_USB_CRC16_ERROR             = 0x65,
SIM_MSG_USB_DFN8_ERROR              = 0x66,
SIM_MSG_USB_BTO_ERROR               = 0x67,
SIM_MSG_USB_DMA_ERROR               = 0x68,
SIM_MSG_USB_RSVD_ERROR              = 0x69,
SIM_MSG_USB_BTS_ERROR               = 0x6A,
SIM_MSG_USB_RCV_TIMEOUT             = 0x6B,
SIM_MSG_USB_CNT_ERROR               = 0x6C,
SIM_MSG_USB_NO_SOF                  = 0x6D,
SIM_MSG_USB_NO_CONNECT              = 0x6E,
SIM_MSG_USB_DATA_ERROR              = 0x6F,
SIM_MSG_USB_WRONG_TOKEN             = 0x70,
SIM_MSG_USB_WRONG_ERROR             = 0x71,
SIM_MSG_USB_AWAKE                   = 0x72,
SIM_MSG_USB_PRE_PID_ERR             = 0x73,
SIM_MSG_USB_PRE_PID_SNT_ERR         = 0x74,
SIM_MSG_USB_ERR_SETUP               = 0x75,
SIM_MSG_USB_OTG_PIN_ERR             = 0x76,
SIM_MSG_USB_POWER_ERR               = 0x77,
SIM_MSG_USB_PWR_VLD_ERR             = 0x78,
SIM_MSG_USB_VBUS_CHG                = 0x79,
SIM_MSG_USB_B_SESS_CHG              = 0x7A,
SIM_MSG_USB_SESS_VLD_CHG            = 0x7B,
SIM_MSG_USB_LINE_STAT_CHG           = 0x7C,
SIM_MSG_USB_ONE_MSEC                = 0x7D,
SIM_MSG_USB_STAT_ID_CHG             = 0x7E,
SIM_MSG_NO_USB                      = 0x7F,
SIM_MSG_USB_DEV_NAK_ERR             = 0x80,
SIM_MSG_USB_DEV_STALL_ERR           = 0x81,
SIM_MSG_USB_SETUP_ERR               = 0x82,
SIM_MSG_USB0_SCHEDULED		    = 0x83,
SIM_MSG_USB1_SCHEDULED		    = 0x84,
SIM_MSG_USB2_SCHEDULED		    = 0x85,
SIM_MSG_USB0_COMPARE  		    = 0x86,
SIM_MSG_USB1_COMPARE  		    = 0x87,
SIM_MSG_USB2_COMPARE  		    = 0x88,
SIM_MSG_USB_DEADMAN  		    = 0x89,
SIM_MSG_USB0_DEADMAN_FAIL           = 0x8A,
SIM_MSG_USB1_DEADMAN_FAIL  	    = 0x8B,
SIM_MSG_USB2_DEADMAN_FAIL           = 0x8C,
SIM_MSG_USB0_COMPARE_FAIL           = 0x8D,
SIM_MSG_USB1_COMPARE_FAIL  	    = 0x8E,
SIM_MSG_USB2_COMPARE_FAIL           = 0x8F,

SIM_MSG_INTR_DMAC_0                 = 0x90,
SIM_MSG_INTR_DMAC_1                 = 0x91,
SIM_MSG_INTR_DMAC_2                 = 0x92,
SIM_MSG_INTR_DMAC_3                 = 0x93,
SIM_MSG_INTR_DMAC_4                 = 0x94,
SIM_MSG_INTR_DMAC_5                 = 0x95,
SIM_MSG_INTR_DMAC_6                 = 0x96,
SIM_MSG_INTR_DMAC_7                 = 0x97,
SIM_MSG_DMAC_TIMEOUT                = 0x98,
SIM_MSG_DMAC_OVERFLOW               = 0x99,
SIM_MSG_DMAC_ABORT                  = 0x9A,
SIM_MSG_DMAC_RELOAD                 = 0x9B,
SIM_MSG_DMAC_COUNT                  = 0x9C,
SIM_MSG_ETH_INTR                    = 0x9D,
SIM_MSG_SCU0_INTR                   = 0x9E,
SIM_MSG_SCU1_INTR                   = 0x9f,
SIM_MSG_KEYPAD_INTR                 = 0xA0,
SIM_MSG_MEMC_INTR                   = 0xA1,
SIM_MSG_PEP_INTR                    = 0xA2,
SIM_MSG_CLRLCD_INTR                 = 0xA3,
SIM_MSG_RES_INTR                    = 0xA4,
SIM_MSG_SDIO_INTR                   = 0xA5,
SIM_MSG_UART3_INTR                  = 0xA6,
SIM_MSG_START_I2C                   = 0xA7,

SIM_MSG_INTR_ERROR                  = 0xAE,
SIM_MSG_GLBL_DATA_INIT              = 0xAF,

SIM_MSG_SDIO_WP_OFF                 = 0xB0,
SIM_MSG_SDIO_CARD_INSERT_ERR        = 0xB1,
SIM_MSG_SDIO_CEATA_ERR              = 0xB2,
SIM_MSG_SDIO_TRG_RESPONCE_ERR       = 0xB3,
SIM_MSG_SDIO_ADMA_ERR               = 0xB4,
SIM_MSG_SDIO_AUTO_CMD_ERR           = 0xB5,
SIM_MSG_SDIO_CURRENT_LIMIT_ERR      = 0xB6,
SIM_MSG_SDIO_DATA_END_BIT_ERR       = 0xB7,
SIM_MSG_SDIO_DATA_CRC_ERR           = 0xB8,
SIM_MSG_SDIO_DATA_TIMEOUT_ERR       = 0xB9,
SIM_MSG_SDIO_CMD_INDEX_ERR          = 0xBA,
SIM_MSG_SDIO_CMD_END_BIT_ERR        = 0xBB,
SIM_MSG_SDIO_CMD_CRC_ERR            = 0xBC,
SIM_MSG_SDIO_CMD_TIMEOUT_ERR        = 0xBD,
SIM_MSG_SDIO_CARD                   = 0xBE,
SIM_MSG_SDIO_CARD_REMOVE            = 0xBF,
SIM_MSG_SDIO_CARD_INSERT            = 0xC0,
SIM_MSG_SDIO_BUFF_READ_RDY          = 0xC1,
SIM_MSG_SDIO_BUFF_WRIT_RDY          = 0xC2,
SIM_MSG_SDIO_DMA_CMPLT              = 0xC3,
SIM_MSG_SDIO_BLK_GAP                = 0xC4,
SIM_MSG_SDIO_TXN_CMPLT              = 0xC5,
SIM_MSG_SDIO_CMD_CMPLT              = 0xC6,
SIM_MSG_SDIO_NO_CARD_INT_ERR        = 0xC7,
SIM_MSG_SDIO_GPIO_CARD_REMOVE       = 0xC8,
SIM_MSG_SDIO_GPIO_CARD_INSERT       = 0xC9,
SIM_MSG_SDIO_BAD_CMD_VALUE          = 0xCA,
SIM_MSG_SDIO_SENT_CMD               = 0xCB,
SIM_MSG_SDIO_CMD_RESP_ERROR         = 0xCC,
SIM_MSG_SDIO_INT_ERROR              = 0xCD,
SIM_MSG_SDIO_CARD_GLITCH            = 0xCE,
SIM_MSG_SDIO_CARD_SWITCH            = 0xCF,

//--- ETHERNET outputs
SIM_MSG_EMAC_SIZES_ERROR            = 0xE0,
SIM_MSG_EMAC_UNEXPECTED_STATUS_ERR  = 0xE1,
SIM_MSG_EMAC_SIZE_WRONG             = 0xE2,
SIM_MSG_EMAC_DATA_WRONG             = 0xE3,
SIM_MSG_EMAC_RX_WRONG               = 0xE4,
SIM_MSG_EMAC_RX_ENABLED             = 0xE5,
SIM_MSG_EMAC_RX_SIZE_ERROR          = 0xE6,
SIM_MSG_EMAC_NO_INIT_ERROR          = 0xE7,
SIM_MSG_EMAC_WRONG_EOF              = 0xE8,
SIM_MSG_EMAC_FILTER_ERROR           = 0xE9,
SIM_MSG_EMAC_EOF_BIT_ERROR          = 0xEA,
SIM_MSG_EMAC_RX_OVERRUN             = 0xEB,
SIM_MSG_EMAC_RX_DONE                = 0xEC,
SIM_MSG_EMAC_RX_PAUSE_CONTROL       = 0xED,
SIM_MSG_EMAC_TX_DONE                = 0xEE,
SIM_MSG_EMAC_TX_PAUSE_CONTROL       = 0xEF,
SIM_MSG_EMAC_MII_MNGMT_DONE         = 0xF0,
SIM_MSG_EMAC_AHB_ERROR              = 0xF1,
SIM_MSG_EMAC_RXBDSTART_ADDR_WRONG   = 0xF2,
SIM_MSG_EMAC_TXBDSTART_ADDR_WRONG   = 0xF3,
SIM_MSG_EMAC_BUFF_DESC_ADDR_ERROR   = 0xF4,
SIM_MSG_EMAC_SOFTWARE_OWN_ERROR     = 0xF5,
SIM_MSG_EMAC_EOF_NOT_SET_ERROR      = 0xF6,
SIM_MSG_EMAC_STATUS_NOT_SET_ERROR   = 0xF7,
SIM_MSG_EMAC_TX_10_DONE             = 0xF8,
SIM_MSG_EMAC_TX_SETUP_DONE          = 0xF9,
SIM_MSG_EMAC_RX_10_DONE             = 0xFA,
SIM_MSG_EMAC_RX_TOO_MANY            = 0xFB,
SIM_MSG_EMAC_TX_TOO_MANY            = 0xFC,
SIM_MSG_EMAC_TF_RXPKTCNT_ERROR      = 0xFD,
SIM_MSG_EMAC_TF_TXPKTCNT_ERROR      = 0xFE,


SIM_MSG_MEMC_SET_CS0                = 0x100,
SIM_MSG_MEMC_SET_CS1                = 0x101,
SIM_MSG_MEMC_SET_CS2                = 0x102,
SIM_MSG_MEMC_SET_CS3                = 0x103,
SIM_MSG_MEMC_SET_CS4                = 0x104,
SIM_MSG_MEMC_SET_CS5                = 0x105,
SIM_MSG_MEMC_SET_KEY0               = 0x108,
SIM_MSG_MEMC_SET_KEY1               = 0x109,

//-- PMU test items
SIM_MSG_PMU_STOP_RTC_DONE           = 0x120,
SIM_MSG_PMU_IDLE_RTC_DONE           = 0x121,

// -- system tests
SIM_MSG_TMR_START                   = 0x200,
SIM_MSG_WDT_START                   = 0x201,
SIM_MSG_LOW_DMA_START               = 0x202,
SIM_MSG_HGH_DMA_START               = 0x203,
SIM_MSG_RNG_START                   = 0x204,
SIM_MSG_MEM_CLEAR                   = 0x205,
SIM_MSG_MEM_CLEAR_DONE              = 0x206,
SIM_MSG_SLEEP_ERROR                 = 0x20A,
SIM_MSG_TASK_START                  = 0x20B,
SIM_MSG_HASH_VERIF_START            = 0x207,
SIM_MSG_HASH_VERIF_DONE             = 0x20C,
SIM_MSG_RESET_ERROR                 = 0x20D,
SIM_MSG_DMA_START                   = 0x208,
SIM_MSG_DMA_END                     = 0x209,
SIM_MSG_DMA_FINISH                  = 0x20E,
SIM_MSG_WORD_VERIF_START            = 0x20F,
SIM_MSG_WORD_VERIF_DONE             = 0x210,
SIM_MSG_WORD_VERIF_ERROR            = 0x211,
SIM_MSG_UART_START                  = 0x212,

// -- system tests
SIM_MSG_SCHED_SLEEP_TASK            = 0x280,
SIM_MSG_SCHED_FIFO_TASK             = 0x281,
SIM_MSG_SCHED_RR_TASK               = 0x282,
SIM_MSG_SCHED_START_FIFO_TASK       = 0x283,
SIM_MSG_SCHED_NO_FIFO_TASK          = 0x284,
SIM_MSG_SCHED_REMOVE_RR_TASK        = 0x285,
SIM_MSG_SCHED_NO_RR_TASK            = 0x286,
SIM_MSG_SCHED_RERUN_RR_TASK         = 0x287,
SIM_MSG_SCHED_START_RR_TASK         = 0x288,
SIM_MSG_SCHED_ADD_TASK              = 0x289,
SIM_MSG_SCHED_BACK_TO_FIFO          = 0x28A,
SIM_MSG_SCHED_ADD_FULL              = 0x28B,
SIM_MSG_SCHED_FIFO_FULL             = 0x28C,
SIM_MSG_SCHED_NO_SUPPORT            = 0x28D,
SIM_MSG_SCHED_RR_RM_TASK            = 0x28E,
SIM_MSG_SCHED_RR_RM_TASK_DIFF       = 0x28F,
SIM_MSG_SCHED_RR_TASK_0_STACK       = 0x290,
SIM_MSG_SCHED_RR_FULL               = 0x291,
SIM_MSG_SCHED_CHRT_RR_ERR           = 0x292,


// -- Color LCD tests
SIM_MSG_CLCD_START                  = 0x300,
SIM_MSG_CLCD_UNDERFLOW_ERROR        = 0x301,
SIM_MSG_CLCD_BUS_ERROR              = 0x302,
SIM_MSG_CLCD_IRQ_OCCURED            = 0x303,
SIM_MSG_CLCD_ADDRESS_RDY            = 0x304,
SIM_MSG_CLCD_VCI_IRQ                = 0x305,
SIM_MSG_CLCD_VERTICAL_SYNC          = 0x306,
SIM_MSG_CLCD_VERTICAL_BACK_PORCH    = 0x307,
SIM_MSG_CLCD_VERTICAL_ACTIVE        = 0x308,
SIM_MSG_CLCD_VERTICAL_FRONT_PORCH   = 0x309,
SIM_MSG_CLCD_END                    = 0x30A,
SIM_MSG_CLCD_SCHEDULED		    = 0x30B,
SIM_MSG_CLCD_STARTED  		    = 0x30C,

SIM_MSG_CRYPT_INTERRUPT		    = 0x380,
SIM_MSG_CRYPT_RAND0    		    = 0x381,
SIM_MSG_CRYPT_CRC0     		    = 0x382,
SIM_MSG_CRYPT_ZERO1    		    = 0x383,
SIM_MSG_CRYPT_SEND     		    = 0x384,
SIM_MSG_CRYPT_CRC1     		    = 0x385,
SIM_MSG_CRYPT_FAIL     		    = 0x386,
SIM_MSG_CRYPT_DEADMAN_CHECK   	    = 0x387,
SIM_MSG_CRYPT_DEADMAN_FAIL    	    = 0x388,

SIM_MSG_LOOP_K                      = 0xFF01,
SIM_MSG_LOOP_J                      = 0xFF00,

SIM_MSG_TEST_PASS                   = 0xFFFE,
SIM_MSG_TEST_FAIL                   = 0xFFFF,

} MSG_ID;


#endif



